### ISSUE TITLE
bug: The bounds of a zone have a negative number in the end coordinates.

### ISSUE THREAD

**Issue by CalSch** [lrstanley/bubblezone#5]
### 🌧 Describe the problem

When I run `zone.Mark()` on a certain string, the start and end coords are the following:
```
StartX: 0
StartY: 0
EndX: -1
EndY: 8
```
Everything is expected except for `EndX`  
The specific string is 8 lines of 16 colored full block characters (█)  

### ⛅ Expected behavior

I expected the coordinates to be:
```
StartX: 0
StartY: 0
EndX: 16
EndY: 8
```

### 🔄 Minimal reproduction

I don't think I can reproduce it because it seems very specific

### 💠 Version: bubblezone

v0.0.0-20220822192435-2c9a0c7b4737

### 🖥 Version: Operating system

linux/ubuntu

### ⚙ Additional context

Maybe block characters aren't counted, but I tried with multiple different characters (#, and space) and it still happened.

### 🤝 Requirements

- [X] I believe the problem I'm facing is a bug, and is not intended behavior. [Post here if you're not sure](../discussions/new?category=q-a).
- [X] I have confirmed that someone else has not [submitted a similar bug report](../labels/bug).

**Comment by CalSch** [comment]
Here's some more info that I left out:  
1. The block characters are styled with lip gloss, but it only changed the foreground.
2. It's for a painting app.
3. Here is the View function:
```go
func (m model) View() string {
	s := ""

	paintScreen := ""

	for y := 0; y < m.height; y++ {
		for x := 0; x < m.width*2; x++ { // Multiply x by 2 because each image pixel is 2 characters wide in the terminal
			color1 := m.img[y][x/2] // Divide x by 2 because of the same reason

			paintScreen += lipgloss.NewStyle().
				Foreground(lipgloss.Color(rgbToHex(color1.r, color1.g, color1.b))).
				Render("█")
				// Render("#")
		}
		paintScreen += "\n"
	}

	s += zone.Mark("paintScreen", paintScreen)

	return zone.Scan(s)
}
```

**Comment by lrstanley** [comment]
Hello @CalSch -- Haven't tested it yet, however, I have a hunch that it's related to the use of `paintScreen += "\n"`. Please see the note in the readme about [how `InBounds()` works](https://github.com/lrstanley/bubblezone#organic-shapes), where we can only check for a block region. When the newline is added before the end zone marker, it means that the zone markers would look something like this:

![bubblezone-newline](https://user-images.githubusercontent.com/1847365/196010380-6a030d5d-48f8-4973-ac8a-90b71f6d4476.png)

As for why it's also `-1` rather than `0`, as you would think from the above diagram, this is because this is what it should normally look like (in the *raw* output):

![bubblezone-no-newline](https://user-images.githubusercontent.com/1847365/196010416-14cf0b4e-9ac2-4cd0-8a79-f0970b231d06.png)

Thus, we always actually calculate the end marker as `x - 1` of it's current `x` position.

I would suggest adding the newline after the call to `zone.Mark()`, and see if that resolves your issues.

**Comment by lrstanley** [comment]
If that does in fact resolve the issues, it does bring up a good point of what the best way of improving the development experience for these kinds of gotchas is. I'm almost thinking that a debug boolean flag can be added where it will panic or throw some kind of error during development when we notice that the end marker doesn't form a positive bounds region, and other potential items like this that we could catch while that debug flag is enabled.

**Comment by CalSch** [comment]
I changed `paintScreen += "\n"` to this:
```go
if y != m.height-1 {
	paintScreen += "\n"
}
```
And it worked perfectly! Thank you very much.  
I think the debug flag would be good addition so if I got an error, I could change `zone.NewGlobal()` to `zone.NewGlobal(true)` or something like that.
